config/routes.rb
GithubApiDemo::Application.routes.draw do
  get "repos/create"
  get "repos/index"

  root 'repos#index'

  get 'repos/download' => 'repos#download'

end

app/models/repo.rb
class Repo < ActiveRecord::Base

  validates :id, presence: true, uniqueness: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/repos_controller.rb
class ReposController < ApplicationController

  def index
    @repos = Repo.all
  end

  def download
    api = 'user/repos'
    github_api_command_string = "\"Authorization: token #{ENV['GITHUB_TOKEN']}\" https://api.github.com/#{api}"
    data = `curl -H #{github_api_command_string}`
    repos = JSON.parse(data)
    repos.each do |repo|
      repo = repo.keep_if { |k,v| k == 'id' || k == 'name' }
      record = Repo.new(repo)
      record.save
    end
    redirect_to repos_index_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/repos_helper.rb
module ReposHelper
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Zurb Foundation %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div data-alert class="alert-box round <%= name == :notice ? "success" : "alert" %>">
      <%= content_tag :div, msg %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Zurb Foundation 5 %>
<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name"><%= link_to 'Home', root_path %></li>
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>
  <div class="top-bar-section">
    <ul>
      <%= render 'layouts/navigation_links' %>
    </ul>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Github Api Demo" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Github Api Demo" %>">
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%# Modernizr is required for Zurb Foundation %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/repos/_repo.html.haml
%br
%repo
= repo.id
%span
= repo.name

app/views/repos/create.html.haml
<h1>Repos#create</h1>
<p>Find me in app/views/repos/create.html.erb</p>

app/views/repos/index.html.haml
%h1 Repos List
= link_to 'Download repos', repos_download_path
= render @repos